SET IDENTITY_INSERT [PersonalityType] ON
INSERT INTO [PersonalityType]
    (Id, [Type], Description, PersonalityPoints)
VALUES 
	(1,  'INFP', 'The Mediator' , 'Idealistic, loyal to their values and to people who are important to them. Want an external life that is congruent with their values. Curious, quick to see possibilities, can be catalysts for implementing ideas. Seek to understand people and to help them fulfill their potential. Adaptable, flexible, and accepting unless a value is threatened.'),
	(2,  'ENFP', 'The Champion' , 'Warmly enthusiastic and imaginative. See life as full of possibilities. Make connections between events and information very quickly, and confidently proceed based on the patterns they see. Want a lot of affirmation from others, and readily give appreciation and support. Spontaneous and flexible, often rely on their ability to improvise and their verbal fluency.'),
	(3,  'INFJ', 'The Advocate' , 'Seek meaning and connection in ideas, relationships, and material possessions. Want to understand what motivates people and are insightful about others. Conscientious and committed to their firm values. Develop a clear vision about how best to serve the common good. Organized and decisive in implementing their vision.'),
	(4,  'ENFJ', 'The Giver'    , 'Warm, empathetic, responsive, and responsible. Highly attuned to the emotions, needs, and motivations of others. Find potential in everyone, want to help others fulfill their potential. May act as catalysts for individual and group growth. Loyal, responsive to praise and criticism. Sociable, facilitate others in a group, and provide inspiring leadership.'),
	(5,  'INTJ', 'The Architect', 'Have original minds and great drive for implementing their ideas and achieving their goals. Quickly see patterns in external events and develop long-range explanatory perspectives. When committed, organize a job and carry it through. Skeptical and independent, have high standards of competence and performance - for themselves and others.'),
	(6,  'ENTJ', 'The Commander', 'Frank, decisive, assume leadership readily. Quickly see illogical and inefficient procedures and policies, develop and implement comprehensive systems to solve organizational problems. Enjoy long-term planning and goal setting. Usually well informed, well read, enjoy expanding their knowledge and passing it on to others. Forceful in presenting their ideas.'),
	(7,  'INTP', 'The Thinker'  , 'Seek to develop logical explanations for everything that interests them. Theoretical and abstract, interested more in ideas than in social interaction. Quiet, contained, flexible, and adaptable. Have unusual ability to focus in depth to solve problems in their area of interest. Skeptical, sometimes critical, always analytical.'),
	(8,  'ENTP', 'The Debater'  , 'Quick, ingenious, stimulating, alert, and outspoken. Resourceful in solving new and challenging problems. Adept at generating conceptual possibilities and then analyzing them strategically. Good at reading other people. Bored by routine, will seldom do the same thing the same way, apt to turn to one new interest after another.'),
    (9,  'ISFP', 'The Artist'   , 'Quiet, friendly, sensitive, and kind. Enjoy the present moment, what is going on around them. Like to have their own space and to work within their own time frame. Loyal and committed to their values and to people who are important to them. Dislike disagreements and conflicts, do not force their opinions or values on others.'),
	(10, 'ESFP', 'The Performer', 'Outgoing, friendly, and accepting. Exuberant lovers of life, people, and material comforts. Enjoy working with others to make things happen. Bring common sense and a realistic approach to their work, and make work fun. Flexible and spontaneous, adapt readily to new people and environments. Learn best by trying a new skill with other people.'),
	(11, 'ISTP', 'The Crafter'  , 'Tolerant and flexible, quiet observers until a problem appears, then act quickly to find workable solutions. Analyze what makes things work and readily get through large amounts of data to isolate the core of practical problems. Interested in cause and effect, organize facts using logical principles, value efficiency.'),
	(12, 'ESTP', 'The Persuader', 'Flexible and tolerant, they take a pragmatic approach focused on immediate results. Theories and conceptual explanations bore them - they want to act energetically to solve the problem. Focus on the here-and-now, spontaneous, enjoy each moment that they can be active with others. Enjoy material comforts and style. Learn best through doing.'),
	(13, 'ISFJ', 'The Protector', 'Quiet, friendly, responsible, and conscientious. Committed and steady in meeting their obligations. Thorough, painstaking, and accurate. Loyal, considerate, notice and remember specifics about people who are important to them, concerned with how others feel. Strive to create an orderly and harmonious environment at work and at home.'),
	(14, 'ESFJ', 'The Caregiver', 'Warmhearted, conscientious, and cooperative. Want harmony in their environment, work with determination to establish it. Like to work with others to complete tasks accurately and on time. Loyal, follow through even in small matters. Notice what others need in their day-by-day lives and try to provide it. Want to be appreciated for who they are and for what they contribute.'),
    (15, 'ISTJ', 'The Inspector', 'Quiet, serious, earn success by thoroughness and dependability. Practical, matter-of-fact, realistic, and responsible. Decide logically what should be done and work toward it steadily, regardless of distractions. Take pleasure in making everything orderly and organized - their work, their home, their life. Value traditions and loyalty.'),
	(16, 'ESTJ', 'The Director' , 'Practical, realistic, matter-of-fact. Decisive, quickly move to implement decisions. Organize projects and people to get things done, focus on getting results in the most efficient way possible. Take care of routine details. Have a clear set of logical standards, systematically follow them and want others to also. Forceful in implementing their plans.');
SET IDENTITY_INSERT [PersonalityType] OFF

-------------------------------------------------------------------------------------------

SET IDENTITY_INSERT [UserType] ON
INSERT INTO [UserType]
    (Id, [Name])
VALUES 
	(1,  'Manager'),
	(2,  'Applicant');
SET IDENTITY_INSERT [UserType] OFF

-------------------------------------------------------------------------------------------

SET IDENTITY_INSERT [Compatibility] ON
INSERT INTO [Compatibility] 
    (Id, ApplicantPersonalityTypeId, ManagerPersonalityTypeId, CompatibilityScore, ScoreExplanation)
VALUES
	-- 1ST LEVEL (INFP)
	(1  ,  1 , 1,  'DARK GREEN' , NULL),
	(2  ,  1 , 2,  'DARK GREEN' , NULL),
	(3  ,  1 , 3,  'DARK GREEN' , NULL),
	(4  ,  1 , 4,  'BLUE'       , NULL),
	(5  ,  1 , 5,  'DARK GREEN' , NULL),
	(6  ,  1 , 6,  'BLUE'       , NULL),
	(7  ,  1 , 7,  'DARK GREEN' , NULL),
	(8  ,  1 , 8,  'DARK GREEN' , NULL),
	(9  ,  1 , 9,  'RED'        , NULL),
	(10 ,  1 , 10, 'RED'        , NULL),
	(11 ,  1 , 11, 'RED'        , NULL),
	(12 ,  1 , 12, 'RED'        , NULL),
	(13 ,  1 , 13, 'RED'        , NULL),
	(14 ,  1 , 14, 'RED'        , NULL),
	(15 ,  1 , 15, 'RED'        , NULL),
	(16 ,  1 , 16, 'RED'        , NULL),
	-- 2ND LEVEL (ENFP)
	(17 ,  2 , 1,  'DARK GREEN' , NULL),
	(18 ,  2 , 2,  'DARK GREEN' , NULL),
	(19 ,  2 , 3,  'BLUE'       , NULL),
	(20 ,  2 , 4,  'DARK GREEN' , NULL),
	(21 ,  2 , 5,  'BLUE'       , NULL),
	(22 ,  2 , 6,  'DARK GREEN' , NULL),
	(23 ,  2 , 7,  'DARK GREEN' , NULL),
	(24 ,  2 , 8,  'DARK GREEN' , NULL),
	(25 ,  2 , 9,  'RED'        , NULL),
	(26 ,  2 , 10, 'RED'        , NULL),
	(27 ,  2 , 11, 'RED'        , NULL),
	(28 ,  2 , 12, 'RED'        , NULL),
	(29 ,  2 , 13, 'RED'        , NULL),
	(30 ,  2 , 14, 'RED'        , NULL),
	(31 ,  2 , 15, 'RED'        , NULL),
	(32 ,  2 , 16, 'RED'        , NULL),
	-- 3RD LEVEL (INFJ)
	(33 ,  3 , 1,  'DARK GREEN' , NULL),
	(34 ,  3 , 2,  'BLUE'       , NULL),
	(35 ,  3 , 3,  'DARK GREEN' , NULL),
	(36 ,  3 , 4,  'DARK GREEN' , NULL),
	(37 ,  3 , 5,  'DARK GREEN' , NULL),
	(38 ,  3 , 6,  'DARK GREEN' , NULL),
	(39 ,  3 , 7,  'DARK GREEN' , NULL),
	(40 ,  3 , 8,  'BLUE'       , NULL),
	(41 ,  3 , 9,  'RED'        , NULL),
	(42 ,  3 , 10, 'RED'        , NULL),
	(43 ,  3 , 11, 'RED'        , NULL),
	(44 ,  3 , 12, 'RED'        , NULL),
	(45 ,  3 , 13, 'RED'        , NULL),
	(46 ,  3 , 14, 'RED'        , NULL),
	(47 ,  3 , 15, 'RED'        , NULL),
	(48 ,  3 , 16, 'RED'        , NULL),
	-- 4TH LEVEL (ENFJ)
	(49 ,  4 , 1,  'BLUE'       , NULL),
	(50 ,  4 , 2,  'DARK GREEN' , NULL),
	(51 ,  4 , 3,  'DARK GREEN' , NULL),
	(52 ,  4 , 4,  'DARK GREEN' , NULL),
	(53 ,  4 , 5,  'DARK GREEN' , NULL),
	(54 ,  4 , 6,  'DARK GREEN' , NULL),
	(55 ,  4 , 7,  'DARK GREEN' , NULL),
	(56 ,  4 , 8,  'DARK GREEN' , NULL),
	(57 ,  4 , 9,  'BLUE'       , NULL),
	(58 ,  4 , 10, 'RED'        , NULL),
	(59 ,  4 , 11, 'RED'        , NULL),
	(60 ,  4 , 12, 'RED'        , NULL),
	(61 ,  4 , 13, 'RED'        , NULL),
	(62 ,  4 , 14, 'RED'        , NULL),
	(63 ,  4 , 15, 'RED'        , NULL),
	(64 ,  4 , 16, 'RED'        , NULL),
	-- 5TH LEVEL (INTJ)
	(65 ,  5 , 1,  'DARK GREEN' , NULL),
	(66 ,  5 , 2,  'BLUE'       , NULL),
	(67 ,  5 , 3,  'DARK GREEN' , NULL),
	(68 ,  5 , 4,  'DARK GREEN' , NULL),
	(69 ,  5 , 5,  'DARK GREEN' , NULL),
	(70 ,  5 , 6,  'DARK GREEN' , NULL),
	(71 ,  5 , 7,  'DARK GREEN' , NULL),
	(72 ,  5 , 8,  'BLUE'       , NULL),
	(73 ,  5 , 9,  'LIGHT GREEN', NULL),
	(74 ,  5 , 10, 'LIGHT GREEN', NULL),
	(75 ,  5 , 11, 'LIGHT GREEN', NULL),
	(76 ,  5 , 12, 'LIGHT GREEN', NULL),
	(77 ,  5 , 13, 'YELLOW'     , NULL),
	(78 ,  5 , 14, 'YELLOW'     , NULL),
	(79 ,  5 , 15, 'YELLOW'     , NULL),
	(80 ,  5 , 16, 'YELLOW'     , NULL),
	-- 6TH LEVEL (ENTJ)
	(81 ,  6 , 1,  'BLUE'       , NULL),
	(82 ,  6 , 2,  'DARK GREEN' , NULL),
	(83 ,  6 , 3,  'DARK GREEN' , NULL),
	(84 ,  6 , 4,  'DARK GREEN' , NULL),
	(85 ,  6 , 5,  'DARK GREEN' , NULL),
	(86 ,  6 , 6,  'DARK GREEN' , NULL),
	(87 ,  6 , 7,  'BLUE'       , NULL),
	(88 ,  6 , 8,  'DARK GREEN' , NULL),
	(89 ,  6 , 9,  'LIGHT GREEN', NULL),
	(90 ,  6 , 10, 'LIGHT GREEN', NULL),
	(91 ,  6 , 11, 'LIGHT GREEN', NULL),
	(92 ,  6 , 12, 'LIGHT GREEN', NULL),
	(93 ,  6 , 13, 'LIGHT GREEN', NULL),
	(94 ,  6 , 14, 'LIGHT GREEN', NULL),
	(95 ,  6 , 15, 'LIGHT GREEN', NULL),
	(96 ,  6 , 16, 'LIGHT GREEN', NULL),
	-- 7TH LEVEL (INTP)
	(97 ,  7 , 1,  'DARK GREEN' , NULL),
	(98 ,  7 , 2,  'DARK GREEN' , NULL),
	(99 ,  7 , 3,  'DARK GREEN' , NULL),
	(100,  7 , 4,  'DARK GREEN' , NULL),
	(101,  7 , 5,  'DARK GREEN' , NULL),
	(102,  7 , 6,  'BLUE'       , NULL),
	(103,  7 , 7,  'DARK GREEN' , NULL),
	(104,  7 , 8,  'DARK GREEN' , NULL),
	(105,  7 , 9,  'LIGHT GREEN', NULL),
	(106,  7 , 10, 'LIGHT GREEN', NULL),
	(107,  7 , 11, 'LIGHT GREEN', NULL),
	(108,  7 , 12, 'LIGHT GREEN', NULL),
	(109,  7 , 13, 'YELLOW'     , NULL),
	(110,  7 , 14, 'YELLOW'     , NULL),
	(111,  7 , 15, 'YELLOW'     , NULL),
	(112,  7 , 16, 'BLUE'       , NULL),
	-- 8TH LEVEL (ENTP)
	(113,  8 , 1,  'DARK GREEN' , NULL),
	(114,  8 , 2,  'DARK GREEN' , NULL),
	(115,  8 , 3,  'BLUE'       , NULL),
	(116,  8 , 4,  'DARK GREEN' , NULL),
	(117,  8 , 5,  'BLUE'       , NULL),
	(118,  8 , 6,  'DARK GREEN' , NULL),
	(119,  8 , 7,  'DARK GREEN' , NULL),
	(120,  8 , 8,  'DARK GREEN' , NULL),
	(121,  8 , 9,  'LIGHT GREEN', NULL),
	(122,  8 , 10, 'LIGHT GREEN', NULL),
	(123,  8 , 11, 'LIGHT GREEN', NULL),
	(124,  8 , 12, 'LIGHT GREEN', NULL),
	(125,  8 , 13, 'YELLOW'     , NULL),
	(126,  8 , 14, 'YELLOW'     , NULL),
	(127,  8 , 15, 'YELLOW'     , NULL),
	(128,  8 , 16, 'YELLOW'     , NULL),
	-- 9TH LEVEL (ISFP)
	(129,  9 , 1,  'RED'        , NULL),
	(130,  9 , 2,  'RED'        , NULL),
	(131,  9 , 3,  'RED'        , NULL),
	(132,  9 , 4,  'BLUE'       , NULL),
	(133,  9 , 5,  'LIGHT GREEN', NULL),
	(134,  9 , 6,  'LIGHT GREEN', NULL),
	(135,  9 , 7,  'LIGHT GREEN', NULL),
	(136,  9 , 8,  'LIGHT GREEN', NULL),
	(137,  9 , 9,  'YELLOW'     , NULL),
	(138,  9 , 10, 'YELLOW'     , NULL),
	(139,  9 , 11, 'YELLOW'     , NULL),
	(140,  9 , 12, 'YELLOW'     , NULL),
	(141,  9 , 13, 'LIGHT GREEN', NULL),
	(142,  9 , 14, 'BLUE'       , NULL),
	(143,  9 , 15, 'LIGHT GREEN', NULL),
	(144,  9 , 16, 'BLUE'       , NULL),
	-- 10TH LEVEL (ESFP)
	(145,  10, 1,  'RED'        , NULL),
	(146,  10, 2,  'RED'        , NULL),
	(147,  10, 3,  'RED'        , NULL),
	(148,  10, 4,  'RED'        , NULL),
	(149,  10, 5,  'LIGHT GREEN', NULL),
	(150,  10, 6,  'LIGHT GREEN', NULL),
	(151,  10, 7,  'LIGHT GREEN', NULL),
	(152,  10, 8,  'LIGHT GREEN', NULL),
	(153,  10, 9,  'YELLOW'     , NULL),
	(154,  10, 10, 'YELLOW'     , NULL),
	(155,  10, 11, 'YELLOW'     , NULL),
	(156,  10, 12, 'YELLOW'     , NULL),
	(157,  10, 13, 'BLUE'       , NULL),
	(158,  10, 14, 'LIGHT GREEN', NULL),
	(159,  10, 15, 'BLUE'       , NULL),
	(160,  10, 16, 'LIGHT GREEN', NULL),
	-- 11TH LEVEL (ISTP)
	(161,  11, 1,  'RED'        , NULL),
	(162,  11, 2,  'RED'        , NULL),
	(163,  11, 3,  'RED'        , NULL),
	(164,  11, 4,  'RED'        , NULL),
	(165,  11, 5,  'LIGHT GREEN', NULL),
	(166,  11, 6,  'LIGHT GREEN', NULL),
	(167,  11, 7,  'LIGHT GREEN', NULL),
	(168,  11, 8,  'LIGHT GREEN', NULL),
	(169,  11, 9,  'YELLOW'     , NULL),
	(170,  11, 10, 'YELLOW'     , NULL),
	(171,  11, 11, 'YELLOW'     , NULL),
	(172,  11, 12, 'YELLOW'     , NULL),
	(173,  11, 13, 'LIGHT GREEN', NULL),
	(174,  11, 14, 'BLUE'       , NULL),
	(175,  11, 15, 'LIGHT GREEN', NULL),
	(176,  11, 16, 'BLUE'       , NULL),
	-- 12TH LEVEL (ESTP)
	(177,  12, 1,  'RED'        , NULL),
	(178,  12, 2,  'RED'        , NULL),
	(179,  12, 3,  'RED'        , NULL),
	(180,  12, 4,  'RED'        , NULL),
	(181,  12, 5,  'LIGHT GREEN', NULL),
	(182,  12, 6,  'LIGHT GREEN', NULL),
	(183,  12, 7,  'LIGHT GREEN', NULL),
	(184,  12, 8,  'LIGHT GREEN', NULL),
	(185,  12, 9,  'YELLOW'     , NULL),
	(186,  12, 10, 'YELLOW'     , NULL),
	(187,  12, 11, 'YELLOW'     , NULL),
	(188,  12, 12, 'YELLOW'     , NULL),
	(189,  12, 13, 'BLUE'       , NULL),
	(190,  12, 14, 'LIGHT GREEN', NULL),
	(191,  12, 15, 'BLUE'       , NULL),
	(192,  12, 16, 'LIGHT GREEN', NULL),
	-- 13TH LEVEL (ISFJ)
	(193,  13, 1,  'RED'        , NULL),
	(194,  13, 2,  'RED'        , NULL),
	(195,  13, 3,  'RED'        , NULL),
	(196,  13, 4,  'RED'        , NULL),
	(197,  13, 5,  'YELLOW'     , NULL),
	(198,  13, 6,  'LIGHT GREEN', NULL),
	(199,  13, 7,  'YELLOW'     , NULL),
	(200,  13, 8,  'YELLOW'     , NULL),
	(201,  13, 9,  'LIGHT GREEN', NULL),
	(202,  13, 10, 'BLUE'       , NULL),
	(203,  13, 11, 'LIGHT GREEN', NULL),
	(204,  13, 12, 'BLUE'       , NULL),
	(205,  13, 13, 'DARK GREEN' , NULL),
	(206,  13, 14, 'DARK GREEN' , NULL),
	(207,  13, 15, 'DARK GREEN' , NULL),
	(208,  13, 16, 'DARK GREEN' , NULL),
	-- 14TH LEVEL (ESFJ)
	(209,  14, 1,  'RED'        , NULL),
	(210,  14, 2,  'RED'        , NULL),
	(211,  14, 3,  'RED'        , NULL),
	(212,  14, 4,  'RED'        , NULL),
	(213,  14, 5,  'YELLOW'     , NULL),
	(214,  14, 6,  'LIGHT GREEN', NULL),
	(215,  14, 7,  'YELLOW'     , NULL),
	(216,  14, 8,  'YELLOW'     , NULL),
	(217,  14, 9,  'BLUE'       , NULL),
	(218,  14, 10, 'LIGHT GREEN', NULL),
	(219,  14, 11, 'BLUE'       , NULL),
	(220,  14, 12, 'LIGHT GREEN', NULL),
	(221,  14, 13, 'DARK GREEN' , NULL),
	(222,  14, 14, 'DARK GREEN' , NULL),
	(223,  14, 15, 'DARK GREEN' , NULL),
	(224,  14, 16, 'DARK GREEN' , NULL),	
	-- 15TH LEVEL (ISTJ)
	(225,  15, 1,  'RED'        , NULL),
	(226,  15, 2,  'RED'        , NULL),
	(227,  15, 3,  'RED'        , NULL),
	(228,  15, 4,  'RED'        , NULL),
	(229,  15, 5,  'YELLOW'     , NULL),
	(230,  15, 6,  'LIGHT GREEN', NULL),
	(231,  15, 7,  'YELLOW'     , NULL),
	(232,  15, 8,  'YELLOW'     , NULL),
	(233,  15, 9,  'LIGHT GREEN', NULL),
	(234,  15, 10, 'BLUE'       , NULL),
	(235,  15, 11, 'LIGHT GREEN', NULL),
	(236,  15, 12, 'BLUE'       , NULL),
	(237,  15, 13, 'DARK GREEN' , NULL),
	(238,  15, 14, 'DARK GREEN' , NULL),
	(239,  15, 15, 'DARK GREEN' , NULL),
	(240,  15, 16, 'DARK GREEN' , NULL),
	-- 16TH LEVEL (ESTJ)
	(241,  16, 1,  'RED'        , NULL),
	(242,  16, 2,  'RED'        , NULL),
	(243,  16, 3,  'RED'        , NULL),
	(244,  16, 4,  'RED'        , NULL),
	(245,  16, 5,  'YELLOW'     , NULL),
	(246,  16, 6,  'LIGHT GREEN', NULL),
	(247,  16, 7,  'BLUE'       , NULL),
	(248,  16, 8,  'YELLOW'     , NULL),
	(249,  16, 9,  'BLUE'       , NULL),
	(250,  16, 10, 'LIGHT GREEN', NULL),
	(251,  16, 11, 'BLUE'       , NULL),
	(252,  16, 12, 'LIGHT GREEN', NULL),
	(253,  16, 13, 'DARK GREEN' , NULL),
	(254,  16, 14, 'DARK GREEN' , NULL),
	(255,  16, 15, 'DARK GREEN' , NULL),
	(256,  16, 16, 'DARK GREEN' , NULL);	
SET IDENTITY_INSERT [Compatibility] OFF

------------------------------------------------------------------------------------------






